[unix_http_server]
file=/home/wentao/project/ops-control-system/supervisor/supervisor.sock

[supervisord]
logfile=/home/wentao/project/ops-control-system/supervisor/supervisord.log
pidfile=/home/wentao/project/ops-control-system/supervisor/supervisord.pid
childlogdir=/home/wentao/project/ops-control-system/supervisor/log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///home/wentao/project/ops-control-system/supervisor/supervisor.sock

[include]
files = /home/wentao/project/ops-control-system/supervisor/conf.d/*.conf
