"""Initial curated Runbooks used by the Agent RAG knowledge base."""

RUNBOOKS = [
    {
        "title": "OPS 控制台無法存取（ocs-backend）",
        "category": "ops", "tags": ["ops", "ocs", "backend", "availability"],
        "affected_assets": ["wentao-MS-7C91", "archlinux"],
        "symptoms": "ops.sanbunto.online 打不開、控制台 502、Agent API 無回應、ocs-backend 停止",
        "description": "診斷並安全恢復 OPS Control System 後端服務。",
        "steps": "1. 檢查公開 HTTPS 與本機 health endpoint。\n2. 檢查 ocs-backend 的 Supervisor 狀態與最近錯誤日誌。\n3. 若服務停止或健康檢查失敗，重啟 ocs-backend。\n4. 再次驗證 API 與公開管理頁。",
        "verification_steps": "本機 Agent health endpoint 回應；https://ops.sanbunto.online/admin/ 回應 200；ocs-backend 顯示 RUNNING。",
        "rollback_steps": "若重啟後持續失敗，停止後續變更、保留日誌與 ExecLog，改為人工檢查部署版本和 .env。",
    },
    {
        "title": "Nginx 502 / upstream 異常",
        "category": "web", "tags": ["nginx", "502", "upstream", "reverse-proxy"],
        "affected_assets": ["archlinux"],
        "symptoms": "Nginx 回傳 502、網站無法開啟、upstream connect error",
        "description": "定位反向代理 upstream、後端服務與 Nginx 設定異常。",
        "steps": "1. 確認 502 的 URL 與對應 upstream。\n2. 檢查 Nginx error log 與設定語法。\n3. 檢查 upstream 服務監聽埠和 Supervisor/Docker 狀態。\n4. 修復後 reload Nginx，避免不必要的 restart。",
        "verification_steps": "nginx -t 成功；目標 URL 回應正常；error log 無新增 upstream error。",
        "rollback_steps": "若新設定 reload 失敗，還原上一版 Nginx 設定並 reload；不要覆寫原設定備份。",
    },
    {
        "title": "FRP 隧道中斷排查與恢復",
        "category": "network", "tags": ["frp", "frps", "frpc", "tunnel"],
        "affected_assets": ["archlinux", "wentao-MS-7C91"],
        "symptoms": "FRP tunnel disconnected、內網服務不可達、frpc/frps offline",
        "description": "檢查 FRP server、client、連接埠與反向代理路由。",
        "steps": "1. 檢查 frps 與 frpc 的服務狀態。\n2. 檢查 FRP dashboard、最近日誌與連線埠。\n3. 確認目標內網服務本身正在監聽。\n4. 僅在診斷證實後重啟對應 frpc 或 frps。",
        "verification_steps": "dashboard 顯示 client online；目標網域 / tunnel 連線恢復；內網服務可達。",
        "rollback_steps": "若重啟不能恢復，停止重試並保留 frpc/frps 日誌；檢查 token、DNS 與雲端防火牆但不得在聊天中顯示憑據。",
    },
    {
        "title": "ComfyUI 服務或佇列卡住",
        "category": "ai", "tags": ["comfyui", "gpu", "queue", "workflow"],
        "affected_assets": ["wentao-MS-7C91"],
        "symptoms": "ComfyUI queue stuck、生成不開始、服務無回應、GPU 任務卡住",
        "description": "檢查 ComfyUI API、佇列、GPU 與受 Supervisor 管理的程序。",
        "steps": "1. 查詢 ComfyUI status、佇列和 GPU 使用狀況。\n2. 查看 ComfyUI 最近日誌，確認是否為模型或工作流錯誤。\n3. 若程序無回應且佇列無進展，確認後重啟 ocs-comfyui。\n4. 以小型工作流或 status endpoint 驗證恢復。",
        "verification_steps": "ComfyUI status 正常；佇列可新增及消化；GPU 程序恢復合理使用率。",
        "rollback_steps": "若重啟後仍失敗，停止反覆重啟，保存日誌並檢查模型、磁碟與 GPU OOM。",
    },
    {
        "title": "Supervisor 服務重啟與日誌排查",
        "category": "service", "tags": ["supervisor", "service", "restart", "logs"],
        "affected_assets": ["archlinux", "wentao-MS-7C91", "vultr"],
        "symptoms": "Supervisor process STOPPED、FATAL、BACKOFF、服務反覆重啟",
        "description": "用 Supervisor 狀態和日誌安全處理受控服務。",
        "steps": "1. 查詢目標 asset 的 Supervisor 狀態。\n2. 讀取 stdout/stderr 與應用程式日誌。\n3. 確認影響與服務依賴後執行單次 restart。\n4. 觀察服務狀態與健康檢查，不得連續盲目重啟。",
        "verification_steps": "程序為 RUNNING；日誌沒有新的 crash loop；關聯服務健康檢查成功。",
        "rollback_steps": "若 restart 導致持續 BACKOFF，停止自動操作、保留日誌、回報需人工處理。",
    },
    {
        "title": "磁碟空間超過閾值",
        "category": "capacity", "tags": ["disk", "storage", "capacity", "cleanup"],
        "affected_assets": ["archlinux", "wentao-MS-7C91", "vultr"],
        "symptoms": "disk usage high、磁碟超過 85%、No space left on device",
        "description": "安全診斷磁碟使用來源，先確認再清理。",
        "steps": "1. 收集磁碟使用率與最大目錄。\n2. 識別日誌、快取、暫存檔或容器資料的可清理候選項。\n3. 先提出精確清理計畫和影響，等待確認。\n4. 執行最小必要清理，再重新收集磁碟指標。",
        "verification_steps": "磁碟使用率低於告警閾值；受影響服務仍正常；未刪除非暫存資料。",
        "rollback_steps": "清理操作通常不可逆；若判斷不明確，禁止刪除，改為人工審核。",
    },


    {
        "title": "SQLite 資料庫備份與恢復", "category": "database",
        "tags": ["sqlite", "backup", "restore", "wal", "ops-db"], "affected_assets": ["wentao-MS-7C91"],
        "symptoms": "資料遺失、資料庫損毀、誤刪資料、備份工作失敗",
        "description": "安全驗證 SQLite 備份並在明確確認後執行還原。",
        "steps": "1. 確認事故範圍與還原時間點；禁止直接覆蓋目前資料庫。\n2. 檢查備份完整性，先複製目前資料庫作為事故快照。\n3. 在隔離副本驗證候選備份與必要資料。\n4. 說明停機、還原與重啟計畫，取得確認後才切換資料庫。\n5. 還原後檢查 health endpoint、資料讀取與 SQLite integrity_check。",
        "verification_steps": "備份可讀取；integrity_check 為 ok；OPS health endpoint 與關鍵資料讀取正常。",
        "rollback_steps": "保留還原前事故快照；驗證失敗時切回快照，不得在原始資料庫上繼續嘗試修復。",
    },
    {
        "title": "OPS 部署失敗或版本回滾", "category": "deploy",
        "tags": ["deploy", "rollback", "git", "frontend", "backend"], "affected_assets": ["wentao-MS-7C91"],
        "symptoms": "部署後網站 5xx、前端空白、health endpoint 失敗、版本功能異常",
        "description": "診斷 OPS 前後端部署問題，使用已知可用版本執行受控回滾。",
        "steps": "1. 記錄目前 commit、部署時間、受影響 URL 與錯誤。\n2. 檢查 git status、服務狀態、建置輸出與日誌。\n3. 未確認根因前不得覆蓋工作區；回滾前先說明資料庫相容性與影響並取得確認。\n4. 切換最後已驗證版本、重新建置前端並重啟目標服務。\n5. 驗證本機 health 與公開 /admin/。",
        "verification_steps": "git status 符合預期；前後端 RUNNING；本機 health 與公開 /admin/ 正常。",
        "rollback_steps": "保留原 commit SHA 與建置紀錄；舊版本也失敗時停止連續切換，改為比對設定與遷移。",
    },
    {
        "title": "HTTPS 憑證到期或 TLS 握手異常", "category": "security",
        "tags": ["tls", "ssl", "certificate", "https", "nginx"], "affected_assets": ["archlinux"],
        "symptoms": "憑證到期、TLS handshake failed、HTTPS 無法連線、憑證鏈不受信任",
        "description": "檢查公開 TLS 憑證、網域解析與 Nginx 設定，安全完成續期或修復。",
        "steps": "1. 確認公開端點的網域、到期日、憑證主體與憑證鏈。\n2. 檢查 DNS、80/443、Nginx 設定與檔案權限。\n3. 確認既有續期方式；不得在聊天中展示私鑰、token 或 DNS API 憑據。\n4. 備份現有設定，通過 nginx -t 後才 reload。\n5. 從外部重新驗證新憑證與 HTTPS 回應。",
        "verification_steps": "憑證網域與有效期限正確；TLS 驗證與 nginx -t 成功；HTTPS URL 正常。",
        "rollback_steps": "新憑證或設定無法驗證時，還原前一份有效設定與憑證後 reload；不要刪除上一份憑證。",
    },
    {
        "title": "SSH 連線失敗與存取權限排查", "category": "access",
        "tags": ["ssh", "access", "permissions", "firewall", "key"], "affected_assets": ["archlinux", "wentao-MS-7C91", "vultr"],
        "symptoms": "Connection refused、Permission denied、SSH timeout、Agent 無法連線至資產",
        "description": "區分網路、服務、帳號與金鑰問題，以最小權限恢復合法 SSH 存取。",
        "steps": "1. 確認資產、連接埠、帳號與錯誤類型。\n2. 檢查網路、雲端防火牆/nftables 與 sshd 監聽狀態。\n3. 對 Permission denied 檢查帳號、authorized_keys 與 sshd 設定；不可顯示私鑰。\n4. 修改存取設定前，提出影響與回復方式並取得確認。\n5. 從授權來源測試一次 SSH。",
        "verification_steps": "指定帳號可從授權來源連線；sshd 正常；防火牆僅開放必要來源與連接埠。",
        "rollback_steps": "變更前保留設定；新規則造成中斷時透過主控台或既有會話還原，不得移除最後一條管理存取路徑。",
    },
    {
        "title": "資料庫鎖定、WAL 成長或 SQLite 完整性異常", "category": "database",
        "tags": ["sqlite", "wal", "locked", "integrity", "performance"], "affected_assets": ["wentao-MS-7C91"],
        "symptoms": "database is locked、請求逾時、WAL 檔異常增長、SQLite integrity_check 失敗",
        "description": "診斷 SQLite 併發、WAL 與完整性問題，避免在線上直接破壞資料。",
        "steps": "1. 收集日誌、請求時間、資料庫/WAL 大小與長時間交易。\n2. 確認連線設定、WAL 模式與寫入鎖。\n3. 唯讀執行 integrity_check 並建立事故快照；不可直接刪除 -wal 或 -shm。\n4. 鎖定持續時受控重啟持有連線的應用程式。\n5. 完整性失敗時依「SQLite 資料庫備份與恢復」Runbook 隔離還原。",
        "verification_steps": "不再出現 database is locked；主要讀寫正常；integrity_check 為 ok；WAL 大小穩定。",
        "rollback_steps": "問題惡化時停止寫入並以事故快照與已驗證備份處理；禁止直接刪除 SQLite 相關檔案。",
    },
    {
        "title": "備份排程失敗與保留策略檢查", "category": "backup",
        "tags": ["backup", "scheduler", "retention", "restore", "monitoring"], "affected_assets": ["wentao-MS-7C91", "archlinux", "vultr"],
        "symptoms": "沒有新備份、備份任務失敗、保留目錄過大、備份檔無法使用",
        "description": "檢查備份排程、儲存容量與可還原性，優先確保資料仍受到保護。",
        "steps": "1. 確認保護目標、頻率、最後成功時間與 RPO/RTO。\n2. 檢查排程、日誌、備份目的地空間與權限。\n3. 驗證最近備份可在隔離位置讀取，不得以測試還原覆蓋正式資料。\n4. 變更排程、刪除舊備份或修改保留策略前必須確認。\n5. 修復後執行一次受控備份並記錄結果。",
        "verification_steps": "排程有下次執行時間；新備份成功且可驗證；目的地有安全餘裕；保留策略符合要求。",
        "rollback_steps": "新排程或保留設定造成失敗時還原前一份設定；不得刪除唯一可用備份。",
    },
]
