"""Initial curated Runbooks used by the Agent RAG knowledge base."""

RUNBOOKS = [
    {
        "title": "OPS 控制台無法存取（ocs-backend）",
        "category": "ops", "tags": ["ops", "ocs", "backend", "availability"],
        "affected_assets": ["wentao-MS-7C91", "archlinux"],
        "symptoms": "ops.sanbunto.online 打不開、控制台 502、Agent API 無回應、ocs-backend 停止",
        "description": "診斷並安全恢復 OPS Control System 後端服務。",
        "steps": "1. 檢查公開 HTTPS 與本機 health endpoint。\n2. 檢查 ocs-backend 的 Supervisor 狀態與最近錯誤日誌。\n3. 若服務停止或健康檢查失敗，重啟 ocs-backend。\n4. 再次驗證 API 與公開管理頁。",
        "verification_steps": "本機 Agent health endpoint 回應；https://ops.sanbunto.online/admin/ 回應 200；ocs-backend 顯示 RUNNING。",
        "rollback_steps": "若重啟後持續失敗，停止後續變更、保留日誌與 ExecLog，改為人工檢查部署版本和 .env。",
    },
    {
        "title": "Nginx 502 / upstream 異常",
        "category": "web", "tags": ["nginx", "502", "upstream", "reverse-proxy"],
        "affected_assets": ["archlinux"],
        "symptoms": "Nginx 回傳 502、網站無法開啟、upstream connect error",
        "description": "定位反向代理 upstream、後端服務與 Nginx 設定異常。",
        "steps": "1. 確認 502 的 URL 與對應 upstream。\n2. 檢查 Nginx error log 與設定語法。\n3. 檢查 upstream 服務監聽埠和 Supervisor/Docker 狀態。\n4. 修復後 reload Nginx，避免不必要的 restart。",
        "verification_steps": "nginx -t 成功；目標 URL 回應正常；error log 無新增 upstream error。",
        "rollback_steps": "若新設定 reload 失敗，還原上一版 Nginx 設定並 reload；不要覆寫原設定備份。",
    },
    {
        "title": "FRP 隧道中斷排查與恢復",
        "category": "network", "tags": ["frp", "frps", "frpc", "tunnel"],
        "affected_assets": ["archlinux", "wentao-MS-7C91"],
        "symptoms": "FRP tunnel disconnected、內網服務不可達、frpc/frps offline",
        "description": "檢查 FRP server、client、連接埠與反向代理路由。",
        "steps": "1. 檢查 frps 與 frpc 的服務狀態。\n2. 檢查 FRP dashboard、最近日誌與連線埠。\n3. 確認目標內網服務本身正在監聽。\n4. 僅在診斷證實後重啟對應 frpc 或 frps。",
        "verification_steps": "dashboard 顯示 client online；目標網域 / tunnel 連線恢復；內網服務可達。",
        "rollback_steps": "若重啟不能恢復，停止重試並保留 frpc/frps 日誌；檢查 token、DNS 與雲端防火牆但不得在聊天中顯示憑據。",
    },
    {
        "title": "ComfyUI 服務或佇列卡住",
        "category": "ai", "tags": ["comfyui", "gpu", "queue", "workflow"],
        "affected_assets": ["wentao-MS-7C91"],
        "symptoms": "ComfyUI queue stuck、生成不開始、服務無回應、GPU 任務卡住",
        "description": "檢查 ComfyUI API、佇列、GPU 與受 Supervisor 管理的程序。",
        "steps": "1. 查詢 ComfyUI status、佇列和 GPU 使用狀況。\n2. 查看 ComfyUI 最近日誌，確認是否為模型或工作流錯誤。\n3. 若程序無回應且佇列無進展，確認後重啟 ocs-comfyui。\n4. 以小型工作流或 status endpoint 驗證恢復。",
        "verification_steps": "ComfyUI status 正常；佇列可新增及消化；GPU 程序恢復合理使用率。",
        "rollback_steps": "若重啟後仍失敗，停止反覆重啟，保存日誌並檢查模型、磁碟與 GPU OOM。",
    },
    {
        "title": "Supervisor 服務重啟與日誌排查",
        "category": "service", "tags": ["supervisor", "service", "restart", "logs"],
        "affected_assets": ["archlinux", "wentao-MS-7C91", "vultr"],
        "symptoms": "Supervisor process STOPPED、FATAL、BACKOFF、服務反覆重啟",
        "description": "用 Supervisor 狀態和日誌安全處理受控服務。",
        "steps": "1. 查詢目標 asset 的 Supervisor 狀態。\n2. 讀取 stdout/stderr 與應用程式日誌。\n3. 確認影響與服務依賴後執行單次 restart。\n4. 觀察服務狀態與健康檢查，不得連續盲目重啟。",
        "verification_steps": "程序為 RUNNING；日誌沒有新的 crash loop；關聯服務健康檢查成功。",
        "rollback_steps": "若 restart 導致持續 BACKOFF，停止自動操作、保留日誌、回報需人工處理。",
    },
    {
        "title": "磁碟空間超過閾值",
        "category": "capacity", "tags": ["disk", "storage", "capacity", "cleanup"],
        "affected_assets": ["archlinux", "wentao-MS-7C91", "vultr"],
        "symptoms": "disk usage high、磁碟超過 85%、No space left on device",
        "description": "安全診斷磁碟使用來源，先確認再清理。",
        "steps": "1. 收集磁碟使用率與最大目錄。\n2. 識別日誌、快取、暫存檔或容器資料的可清理候選項。\n3. 先提出精確清理計畫和影響，等待確認。\n4. 執行最小必要清理，再重新收集磁碟指標。",
        "verification_steps": "磁碟使用率低於告警閾值；受影響服務仍正常；未刪除非暫存資料。",
        "rollback_steps": "清理操作通常不可逆；若判斷不明確，禁止刪除，改為人工審核。",
    },
]
